# Site settings
title: Veggies.io
email: your-email@domain.com
description: Simplify healthy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "veggies.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Add Vegetable 
collections:
    vegetables:
        output: true

sass:
  style: :compressed