# Site settings
title: Eat Your Veggies
email: your-email@domain.com
description: Simplify healthy.
baseurl: "eat-your-veggies" # the subpath of your site, e.g. /blog/
url: "http://joshre.github.io/eat-your-veggies/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Add Vegetable 
collections:
    vegetables:
        output: true

sass:
  style: :compressed